version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodedb
    volumes:
      - /home/prgomesr/full-cycle/volumes/data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - node-network

networks:
  node-network:
    driver: bridge
